# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nishant Kelkar's Blog
email: nishant.k02@gmail.com
description: # >- # this means to ignore newlines until "baseurl:"
  This is a blog built with Jekyll
baseurl: ""
url: "https://nishantkelkar-blog.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# github_username:  nishantkelkar-blog

# For tags via jekyll-tagging
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# Build settings
markdown: kramdown
permalink: /:title
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# To configure the navigation bar...nothing else seems to work!
header_pages:
  - about.md
  - blog.html
  - index.html
